// <auto-generated />
using System;
using HomeAssignmentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeAssignmentAPI.Migrations
{
    [DbContext(typeof(HomeAssignmentAPIContext))]
    partial class HomeAssignmentAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeAssignmentAPI.Models.EquipmentList", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquipmentType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("EquipmentList");

                    b.HasData(
                        new
                        {
                            Name = "Caterpillar bulldozer",
                            EquipmentType = "Heavy"
                        },
                        new
                        {
                            Name = "KamAZ truck",
                            EquipmentType = "Regular"
                        },
                        new
                        {
                            Name = "Komatsu crane",
                            EquipmentType = "Heavy"
                        },
                        new
                        {
                            Name = "Volvo steamroller",
                            EquipmentType = "Regular"
                        },
                        new
                        {
                            Name = "Bosch jackhammer",
                            EquipmentType = "Specialized"
                        });
                });

            modelBuilder.Entity("HomeAssignmentAPI.Models.RentedHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RentedDays")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RentedHistory");
                });

            modelBuilder.Entity("HomeAssignmentAPI.Models.RentedHistory", b =>
                {
                    b.HasOne("HomeAssignmentAPI.Models.EquipmentList", "EquipmentList")
                        .WithMany("RentedHistories")
                        .HasForeignKey("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
